language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

before_script:
  - yarn

script:
  - yarn run cosmos:export

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: cosmos-export
  on:
    branch: master
